### ISSUE TITLE
Connection issues on server with multiple network devices.

### ISSUE THREAD

**Issue by gillhofer** [n-i-x/pc-autobackup#8]
I've a NX3000 and your tool works great on my desktop (Arch Linux). Unfortunately, not on my always running home server. 

By using the ` --create_camera_config` parameter, the config file gets written with a local MAC Address (device: *p4p1*) , presumably the first one from `ifconfig`?. In my configuration the correct port would be the second one, which is connected to the internal network (device: *br0*). 

However, It would be cool if I could choose which port the camera should bind to while connecting. 

Changing the MAC Adress manually was not succesfull. I guess the UUID also needs some adjustment. But don't know enough about UPnP.

**Comment by n-i-x** [comment]
The MAC address is only used for the WOL function to send the magic packet to your server. Most people don't use that feature and if your server is always running you won't use it either.

Are you saying that it sometimes works on your home server but there are times where it doesn't? There could be a number of reasons for sporadic issues ranging from multiple UPnP servers listening, binding the daemon to the wrong IP (most common), routers/firewalls filtering UPnP packets, etc.

**Comment by gillhofer** [comment]
The bad thing is. It never worked on my home-server (which is also used as my internet-wlan-router).

I used wireshark to find a difference in the traffic between both machines, and it looks like a problem with "UPnP membership reports" in the IGMP protocoll, and thus the bug is likely within my machines iptables rules.

However, I now think it's is a local problem. 

As I don't know how to investigate any further. could you sketch the connection set-up process of the camera with this software?

**Comment by n-i-x** [comment]
You could also start the daemon with --bind and it will start on the IP you selected.

**Comment by birgerro** [comment]
I have made a summary of the backup process from a packet capture when backing up one picture, maybe that will be of use? The server had ip address 192.168.1.20, while the camera had ip address 192.168.1.150. I tried to upload the zip file, but github didn't like that, so I include a link instead:

     https://googledrive.com/host/0BxBOCo4qJ8ZrclVtTGJ1V1o1cHc/backup_process.zip

The short version:
1) The camera sends an udp multicast to 239.255.255.250:1900 (from 192.168.1.150:24234)
2) The server replies with an udp packet back to 192.168.1.150:24234 (from 192.168.1.20:1900) which includes an ip address and port number (192.168.1.20:52235)
3) The camera uses tcp http GET to request several xml documents (SamsungDmsDesc.xml, ContentDirectory1.xml, ConnectionManager1.xml) from 192.168.1.20:52235
4) The camera uses tcp http POST to start backup (X_BACKUP_START), which includes number of images to back up
5) For each image, the camera uses tcp http POST to CreateObject, and then tcp http POST to transfer the binary data
6) Finally, the camera uses tcp http POST to signal end of backup (X_BACKUP_DONE)

As a final comment, with my camera (WB350F) it seems like the camera uses the src ip address instead of the included ip address in step 2, so even with a wrongly configured server (for instance with ip 127.0.1.1), the process will continue until after CreateObject in step 5. In the second half of step 5, the camera tries to send data to the included address, at the process stops if the ip cannot be reached.
